<!DOCTYPE html>
<html lang="en-US">

<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<meta charset="UTF-8">
	<title>About Us</title>
	<link rel="stylesheet" type="text/css" media="all" href="css/reset.css"></link>
	<link rel="stylesheet" type="text/css" media="all" href="css/zband.css"></link>
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-35488053-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>
</head>

<body class="home blog">
	  <div id="page-wrapper">
		<?php include("ZBand-Header.php"); ?>

		<div id="page-body">
			<div class="generic-main">
				<div class="top-section">
					<h1>Members of the Band</h1>
				</div>
				<div class="middle-section">

					<!--Add Content Here-->

					<div class="article-divide">

					<span class="article-left-heading-about" style="color:white !important;"> <span style="font-size: 45px;">Paul Griffin</span> Co-Founder</span>
					<div class="article-wide-right">
						<p>
						I'm a guy in my 30s from a great place called County Mayo on the west coast
						of Ireland. I never liked noisy alarms and in the summer of 2009 came up with
						an idea for a silent alarm. Many people have great ideas but just do not have
						the time to pursue them. Having thought about the ZBand for several months,
						in January 2010 I decided it was time to do or die. Some of the best ideas
						come from necessity and I wanted to develop a waking up solution that would
						improve my quality of life. So I took the plunge to bring the ZBand from idea to
						reality.
						</p>
						<p>
						Initially I thought it would take a year at most to develop the ZBand. In fact it
						has taken three years' of hard work, while at the same time doing the day job
						to pay the bills. Throughout the period of development, my family and friends
						always believed in me and believed in the ZBand but they thought I was a little
						mad to put so much time and resources into it. I think, and I hope you'll agree,
						that the ZBand has been worth the effort.
						</p>
						<p>
						Almost a decade ago I started my own company in Ireland. Even though the
						country has experienced the deepest recession in its history, my company
						has remained strong. This is due to our professionalism, high quality product,
						attention to detail and reliability qualities that characterize the ZBand.
						</p>

					</div>

					<div class="article-image-profile-left"></div>
					</div>




					<div class="article-divide">

					<span class="article-right-heading-about"> <span style="font-size: 45px;">Declan Leonard</span> Co-Founder</span>
					<div class="article-wide-left-about">
					Similar to Paul, I'm in my 30's and a fellow Mayo man from the west of Ireland. I've known Paul for many years now as we met
					as students in the University of Limerick and we both live and work in Dublin. One fine summer's day Paul came to me with the
					concept for the ZBand. I really liked it. Like all good ideas, it was simple. I immediately thought, why didn't I think of
					this years ago. Anyway, with my background in IT I was well placed to help Paul to bring the ZBand from an embryonic concept
					to the real physical product and phone application we see before us. It's been a long hard road, but it's worth it. I hope you
					enjoy the fruits of our labour.

					</div>

					<div class="article-image-profile-left-2"></div>
					</div>


				</div>
			</div>

		</div><!-- end of #page-body -->


		<?php include("ZBand-Footer.php"); ?>










	</div><!-- end of #page-wrapper -->

	<div id="wp_footer">
		</div>






</body>
</html>
<!-- Dynamic page generated in 0.908 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2011-12-06 10:59:45 -->
<!-- super cache -->