<!DOCTYPE html>
<html lang="en-US">

<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<meta charset="UTF-8">
	<title>Download</title>
	<link rel="stylesheet" type="text/css" media="all" href="css/reset.css"></link>
	<link rel="stylesheet" type="text/css" media="all" href="css/zband.css"></link>
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-35488053-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>

</head>

<body class="home blog">
	  <div id="page-wrapper">
		<?php include("ZBand-Header.php"); ?>

		<div id="page-body">
			<div class="generic-main" >
				<div class="top-section">
					<h1>Download</h1>
				</div>
				<div class="middle-section">
					<div class="banner-image" style="width:917px">
					</div>
					<h3>Android</h3>

						<div class="answer">
							<p>Download the Android App for your Android phone or tablet from the Google Play store <a href="https://play.google.com/store/apps/details?id=com.zband&feature=search_result#?t=W251bGwsMSwyLDEsImNvbS56YmFuZCJd">here</a></p>
						</div>

					<h3>Windows Deskop and Laptop</h3>

						<div class="answer">
							<p>Download the Windows Desktop and Laptop application <a  href="../ZBandSetup.exe">here</a></p>

						</div>

					<h3>Windows 8 Mobile</h3>

						<div class="answer">
							<p>Download the Windows 8 Mobile App for your Windows 8 phone or tablet from the Windows App store <a href="http://www.windowsphone.com/en-us/store/app/zband/8e5c4451-0457-4bde-8a0c-8d6f03be913e">here</a></p>
						</div>

				</div>
			</div>

		</div><!-- end of #page-body -->
		<div style="clear:both"></div>

		<?php include("ZBand-Footer.php"); ?>










	</div><!-- end of #page-wrapper -->

	<div id="wp_footer">
		</div>






</body>
</html>
<!-- Dynamic page generated in 0.908 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2011-12-06 10:59:45 -->
<!-- super cache -->