<!DOCTYPE html>
<html lang="en-US">

<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<meta charset="UTF-8">
	<title>Zband</title>
	<link rel="stylesheet" type="text/css" media="all" href="css/reset.css"></link>
	<link rel="stylesheet" type="text/css" media="all" href="css/zband.css"></link>
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-35488053-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>

</head>

<body class="home blog">
	  <div id="page-wrapper">
		<?php include("ZBand-Header.php"); ?>

		<div id="page-body">
			<div class="generic-main">
				<div class="top-section">
					<h1>FAQ</h1>
				</div>
				<div class="middle-section">
					<div class="banner-image">
					</div>
					<h3>What platforms is the ZBand application available for?</h3>
						<div class="answer">
							<p>Android and Windows Phone 8 for smart phones and tablets. Windows 8 Desktop, Windows 7, Windows Vista for Windows desktop. Your laptop or desktop will need to have bluetooth (or a bluetooth dongle) to communicate with the ZBand. You can download the Apps for the supported platforms <a href='download.php'>here</a></p>
						</div>
					<h3>Can I download the ZBand App to my android or windows tablet?</h3>
						<div class="answer">
							<p>Yes, the Zband App can be downloaded to any Android phone or tablet.
							The device must have Bluetooth to set alarms on the ZBand.</p>
						</div>

					<h3>My Windows desktop or laptop does not have bluetooth, can I still use the ZBand?</h3>
						<div class="answer">
							<p>As the ZBand is set using bluetooth you can plug in a bluetooth dongle into your desktop or laptop to use the ZBand. We don't stock the bluetooth dongle at present but plan to in the near future. They are available for on Amazon for less that $10</p>
						</div>


					<h3>Does the device have to be in Bluetooth range for the alarm on the ZBand to go off?</h3>
						<div class="answer">
							<p>No, the device is used to set alarms on the ZBand, once alarms are set on the ZBand
							the android device does not need to be connected to the ZBand.</p>
						</div>
					<h3>How do I get started on the ZBand?</h3>
						<div class="answer">
							<p>Please read the instruction manual supplied with the ZBand. You can also click <a href="about-zband.php">here</a> to view a short video with guidelines.</p>
						</div>
					<h3>How do I set the vibration strength for the ZBand?</h3>
						<div class="answer">
							<p>After downloading the ZBand app and paring the ZBand to the android device you can connect the
							android device to the ZBand as shown on the instruction manual. When connected the ZBand app will
							show a screen with 3 tabs at the top of the screen. The 3 tabs are alarms, snooze function
							and vibration strength. Press the vibration strength tab and set vibration strength and
							then press save settings.</p>
						</div>
					<h3>On the set alarm screen, what does the name mean?</h3>
						<div class="answer">
							<p>This gives the user an option to name each alarm for different settings. The user does not need to
							name alarm if they do not wish to and can carry onto save alarm.</p>
						</div>
					<h3>How long does the ZBand last without a charge?</h3>
						<div class="answer">
							<p>The ZBand will last approximately 10 days of regular use on a 30 minute charge. To charge the ZBand
							you can use any macro USB charger which is the standard charger for nearly all android smartphones.</p>
						</div>
					<h3>Can I use other alarms on my device while using the ZBand?</h3>
						<div class="answer">
							<p>Yes, the ZBand does not interfere with any other alarm on the users device, therefore the ZBand
							can be use on its own or in conjunction with another alarm.</p>
						</div>
				</div>
			</div>

		</div><!-- end of #page-body -->


		<?php include("ZBand-Footer.php"); ?>










	</div><!-- end of #page-wrapper -->

	<div id="wp_footer">
		</div>






</body>
</html>
<!-- Dynamic page generated in 0.908 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2011-12-06 10:59:45 -->
<!-- super cache -->