<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="http://www.facebook.com/2008/fbml">

<!--Fix backgound black/grey-->


<head>

	<title>Zband Silent Alarm</title>
	<meta name="Description" content="ZBand is the world's first silent alarm vibrating wristband for Android and Windows" />
	<meta name="Keywords" content="ZBand, silent alarm, vibrating wristband, android, gift" />
	<link rel="stylesheet" type="text/css" media="all" href="css/reset.css"></link>
	<link rel="stylesheet" type="text/css" media="all" href="css/zband.css"></link>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<meta charset="UTF-8">
	<meta property="og:title" content="Zband Silent Alarm Wristband" />
	<meta property="og:type" content="product" />
	<meta property="og:url" content="http://zband.biz" />
	<meta property="og:image" content="http://zband.biz/images/facebook-logo.png" />
	<meta property="og:site_name" content="ZBand" />
	<meta property="fb:admins" content="100004433681886" />

	<script type="text/javascript">
	function submitform()
	{
	  document.forms[0].submit();
	}
	</script>
	<script language="JavaScript" src="http://www.geoplugin.net/javascript.gp" type="text/javascript"></script>
</head>


<body class="home blog">

<div id="fb-root"></div>

	  <div id="page-wrapper">
		<?php include("ZBand-Header.php"); ?>
				<div id="page-body">
				<div class="home-main">


							<div class="buybtn">

								<!--
								<a href="http://www.indiegogo.com/ZBand">
								<img style="float: left;" border="0" alt="W3Schools" src="images/pre-order.png" width="100" height="60">
								</a>
								-->
								<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
									<input type="hidden" name="cmd" value="_s-xclick">
									<input type="hidden" name="hosted_button_id" value="AZHFZTCRHNR6J">
									<input type="image" src="http://www.zband.biz/images/buy-button.png" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
									<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
								</form>

							</div>




					<div class="dummy-image"></div>
					<div class="dummy-android"></div>
					<div class="zband-promo zband-promo">

			  <ul class="promo-images">
					<li id="zband-promo-0" class="promo-image 0 first selected last">

					<h2>Feel the</h2><div class="logoSlogan"></div>
					<div class="promo_content"><p>ZBand is the world's first silent alarm vibrating wristband for Android and Windows</p>
			</div>

				  </li>
				</ul>

	  <ul class="promo-icons">

			<li class="promo-icon 0 first selected last">
			<a href="#zband-promo-0"></a>
		  </li>

	  </ul>

	</div>
			<div class="content-inset clearfix">

				<div class="zb-main">
					<h2>Counttry code is <script>alert(geoplugin_countryCode());</script></h2>

				</div>

				<div class="zb-group">

					<div class="zb-sub">
					</div>

					<div class="zb-sub">

					</div>

				</div>

			</div>



		</div>

		</div><!-- end of #page-body -->


		<?php include("ZBand-Footer.php"); ?>


	</div><!-- end of #page-wrapper -->

	<div id="wp_footer">
		</div>






</body>
</html>
<!-- Dynamic page generated in 0.908 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2011-12-06 10:59:45 -->
<!-- super cache -->